# -*- coding: utf-8 -*-
"""studentdatabase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CTzVUuDtu0Ab_gX-t86fF7o0G6578eL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")
df

categorical_columns = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

for col in categorical_columns:
  df[col] = df[col].str.strip().str.title()

for col in categorical_columns:
  print(df[col].head())

score_column = df[["math score","reading score","writing score"]]

score_column.describe()

df['total marks'] = df["math score"]+df["reading score"]+df["reading score"]

df.head()

df['percentage'] = (df['total marks']/300)*100

df.head()

df.tail()

df.info()

df.isnull().sum()

